# Generated by Django 5.0.6 on 2024-07-23 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('density', models.FloatField()),
                ('grade', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WeighbridgeTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='density',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='product_name',
        ),
        migrations.AlterField(
            model_name='truck',
            name='vehicle_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='material',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trucks.truck'),
        ),
        migrations.AddField(
            model_name='weighbridgeticket',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trucks.truck'),
        ),
        migrations.DeleteModel(
            name='CustomerSupport',
        ),
    ]
